[package]
name = "figment-wrapper"
version = "0.2.0"
edition = "2021"

[dependencies]
quote = "1.0.35"
syn = { version = "2.0.48",features = ["parsing"] }
proc-macro2 = "1.0.76"

[lib]
proc-macro = true
