[package]
name = "agordo"
version = "0.1.0"
edition = "2018"

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
serde = { version = "1.0", features = ["derive","rc"] }

[lib]
proc-macro = true
